### ISSUE TITLE
How to handle images?

### ISSUE THREAD

**Issue by bogdan-pechounov** [Aghajari/AnnotatedText#1]
I tried creating an `Html.ImageGetter`, but the image is loaded asynchronously.

```
import android.content.Context
import android.content.res.Resources
import android.graphics.Bitmap
import android.graphics.drawable.BitmapDrawable
import android.graphics.drawable.Drawable
import android.text.Html
import android.util.Log
import coil.Coil
import coil.request.ImageRequest

class CoilImageGetter(
    val context: Context
) : Html.ImageGetter {

    override fun getDrawable(source: String): Drawable {
        Log.d("IMAGE", source)
        val placeHolder = BitmapDrawablePlaceHolder(context.resources, null)
        val imageLoader = Coil.imageLoader(context)
        val request = ImageRequest.Builder(context)
            .data(source)
            .target { drawable ->
                Log.d("IMAGE", "img: $drawable")
                placeHolder.setDrawable(drawable)
            }
            .build()
        imageLoader.enqueue(request)
        return placeHolder
    }

    private class BitmapDrawablePlaceHolder(res: Resources, bitmap: Bitmap?) :
        BitmapDrawable(res, bitmap) {
        private var drawable: Drawable? = null

        override fun draw(canvas: android.graphics.Canvas) {
            drawable?.run { draw(canvas) }
        }

        fun setDrawable(drawable: Drawable) {
            this.drawable = drawable
        }
    }
}
```
That means that the bitmap is null initially. 
```
13:51:05.765  D  //upload.wikimedia.org/wikipedia/en/thumb/5/5f/Disambig_gray.svg/30px-Disambig_gray.svg.png
13:51:17.512  D  //upload.wikimedia.org/wikipedia/en/thumb/5/5f/Disambig_gray.svg/30px-Disambig_gray.svg.png
13:51:17.538  E  FATAL EXCEPTION: main
                 Process: com.example, PID: 22285
                 java.lang.IllegalArgumentException: bitmap is null
                 	at androidx.core.graphics.drawable.DrawableKt.toBitmap(Drawable.kt:54)
                 	at androidx.core.graphics.drawable.DrawableKt.toBitmap$default(Drawable.kt:46)
                 	at com.aghajari.compose.text.DimensionsKt.toImageBitmap(Dimensions.kt:42)
                 	at com.aghajari.compose.text.ImageInlineContentCreator.onCreate(ImageInline.kt:32)
                 	at com.aghajari.compose.text.InlineContentKt.getInlineContentMap(InlineContent.kt:45)
                 	at com.aghajari.compose.text.AnnotatedTextKt.AnnotatedText-edWjEy0(AnnotatedText.kt:88)
                 	at com.example.ui.screens.main.MainScreenKt.MainScreen(MainScreen.kt:82)
                 	at com.example.ui.screens.main.MainScreenKt$MainScreen$2.invoke(Unknown Source:12)
                 	at com.example.ui.screens.main.MainScreenKt$MainScreen$2.invoke(Unknown Source:10)
                 	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:162)
                 	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2465)
                 	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2733)
                 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3364)
                 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3342)
                 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
                 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
                 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3342)
                 	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3307)
                 	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:772)
                 	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1047)
                 	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
                 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:541)
                 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:510)
                 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1230)
                 	at android.view.Choreographer.doCallbacks(Choreographer.java:1029)
                 	at android.view.Choreographer.doFrame(Choreographer.java:925)
                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217)
                 	at android.os.Handler.handleCallback(Handler.java:938)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:233)
                 	at android.os.Looper.loop(Looper.java:344)
                 	at android.app.ActivityThread.main(ActivityThread.java:8212)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
                 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@2c8e2c8, androidx.compose.ui.platform.MotionDurationScaleImpl@351af61, StandaloneCoroutine{Cancelling}@33d6a86, AndroidUiDispatcher@13f5f47]
```

**Comment by Aghajari** [comment]
Hello @bogdan-pechounov ,

It seems that achieving asynchronous image loading with a custom `Html.ImageGetter` is indeed a challenging task, I appreciate your dedication in trying to make it work.

I have a solution that should help you achieve asynchronous image loading using Coil. Instead of relying on `Html.ImageGetter`, we can create a custom `InlineTextContent` map for more control over image loading.

Note that to use Coil's `AsyncImage`, we need to know the dimensions of each image from its source. This information is crucial for displaying images properly. 

**Add the following code into your project:**

```kotlin
import android.os.Build
import android.text.style.DynamicDrawableSpan
import android.text.style.ImageSpan
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.text.InlineTextContent
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.Placeholder
import androidx.compose.ui.text.PlaceholderVerticalAlign
import androidx.compose.ui.unit.TextUnit
import coil.compose.AsyncImage
import com.aghajari.compose.text.ContentAnnotatedString
import com.aghajari.compose.text.InlineContent

private fun coilImageInlineContentCreator(
    content: InlineContent,
    width: TextUnit,
    height: TextUnit
): InlineTextContent {
    val span = content.span as ImageSpan

    return InlineTextContent(
        placeholder = Placeholder(
            width = width,
            height = height,
            when (span.verticalAlignment) {
                DynamicDrawableSpan.ALIGN_BOTTOM -> {
                    PlaceholderVerticalAlign.TextBottom
                }
                DynamicDrawableSpan.ALIGN_CENTER -> {
                    PlaceholderVerticalAlign.TextCenter
                }
                DynamicDrawableSpan.ALIGN_BASELINE -> {
                    PlaceholderVerticalAlign.AboveBaseline
                }
                else -> {
                    PlaceholderVerticalAlign.TextTop
                }
            }
        )
    ) {
        val desc = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            span.contentDescription?.toString()
        } else {
            null
        }

        AsyncImage(
            model = span.source,
            contentDescription = desc,
            modifier = Modifier.fillMaxSize()
        )
    }
}

fun ContentAnnotatedString.getCoilInlineContentMap(
    size: (InlineContent) -> Pair<TextUnit, TextUnit>
): Map<String, InlineTextContent> {
    val map = LinkedHashMap<String, InlineTextContent>(inlineContents.size)
    inlineContents.forEach { content ->
        val sizePair = size(content)
        map[content.id] = coilImageInlineContentCreator(
            content = content,
            width = sizePair.first,
            height = sizePair.second
        )
    }
    return map
}
```

**At the end, you can use it as follows:**

```kotlin
AnnotatedText(
    text = myText,
    inlineContent = myText.getCoilInlineContentMap { content ->
        // Define the dimensions for your images, for example:
        val imageWidth = 16.sp
        val imageHeight = 16.sp
        imageWidth to imageHeight
    },
    fontSize = 16.sp,
    ...
)
```

If you have any questions or need further assistance with this implementation, please feel free to reach out.

**Comment by bogdan-pechounov** [comment]
I see, this approach makes more sense. Thank you for the help and for your time!

I just had to add `"https:${span.source}"`, because Wikipedia doesn't include it for some reason and the source looks like this: `//upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Red_pog.svg/8px-Red_pog.svg.png`.

**Comment by Philipp91** [comment]
> Note that to use Coil's AsyncImage, we need to know the dimensions of each image from its source.

I don't think this is a fair assumption to make. If I use regular `parseHtml()` and put the result into a good old `TextView`, it can load images dynamically, e.g. using the code from https://stackoverflow.com/a/77798251. Though note how that contains that `textView.text = textView.text` workaround, which seems to be a way of notifying the UI that the image has been loaded and hence the UI needs to re-read and re-render the `Spanned` string.

Is there a better solution? Ideally, I'd write `<img src="http://example.com/image.png"/>` in the original HTML, coil would load the file from the server and cache it locally, and the `AnnotatedText` would display it whenever it's ready.

**Comment by Philipp91** [comment]
I think I found a simpler solution, by using `AsyncImage(onSuccess=...)` to put the image size into some `State` (map), which when updated will trigger a rerender of the `AnnotatedText` where we can then fill in the size dynamically:

```kt
    // Make all images full-width within this component. And until we know the component's width, use the screen width.
    val view = LocalView.current
    val density = LocalDensity.current
    val estimatedWidthPx = with(density) {
        view.width // Feel free to subtract any known padding here.
    }
    var outputWidthPx by remember { mutableIntStateOf(estimatedWidthPx) }

    // Use AsyncImage and an appropriately sized Placeholder for each image.
    val imageHeights = remember { mutableStateMapOf<String, Int>() }
    val inlineContent = remember {
        derivedStateOf {
            myText.inlineContents.associate { content ->
                val span = content.span as ImageSpan
                val url = span.source!!
                val imageHeightPx = // Estimate square image, except `data:` often means tiny image.
                    imageHeights[url] ?: if (url.startsWith("data:")) 0 else outputWidthPx
                content.id to InlineTextContent(
                    placeholder = Placeholder(
                        width = with(density) { outputWidthPx.toSp() },
                        height = with(density) { imageHeightPx.toSp() },
                        when (span.verticalAlignment) {
                            DynamicDrawableSpan.ALIGN_BOTTOM -> PlaceholderVerticalAlign.TextBottom
                            DynamicDrawableSpan.ALIGN_CENTER -> PlaceholderVerticalAlign.TextCenter
                            DynamicDrawableSpan.ALIGN_BASELINE -> PlaceholderVerticalAlign.AboveBaseline
                            else -> PlaceholderVerticalAlign.TextTop
                        }
                    )
                ) {
                    AsyncImage(
                        model = url,
                        contentDescription = span.contentDescription?.toString(),
                        modifier = Modifier.fillMaxSize(),
                        onSuccess = { state ->
                            val image = state.result.image
                            imageHeights[url] = outputWidthPx * image.height / image.width
                        },
                    )
                }
            }
        }
    }

    AnnotatedText(
        parsedHtml,
        Modifier.onSizeChanged { outputWidthPx = with(density) { it.width } },
        inlineContent = inlineContent.value,
    )
```
